#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

name: Make Openlist2 Run File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fetch latest release tag from openlist2
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/sbwml/luci-app-openlist2/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          
      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest openlist2 files
        run: |
          # 下载最新 release 的两个架构包
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-openlist2/releases/latest | grep -oP '"browser_download_url":\s*".*openwrt-24.10-aarch64_cortex-a53.tar.gz"' | cut -d '"' -f 4) 
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-openlist2/releases/latest | grep -oP '"browser_download_url":\s*".*openwrt-24.10-x86_64.tar.gz"' | cut -d '"' -f 4)
          # 解压并分别重命名 packages_ci 目录
          tar -xvzf *aarch64_cortex-a53.tar.gz
          mv packages_ci openlist2_aarch64_cortex-a53
          tar -xvzf *x86_64.tar.gz
          mv packages_ci openlist2_x86_64

      - name: Organize files for aarch64_cortex-a53&x86_64
        run: |
          # 保存当前路径并进入目标目录
          pushd "openlist2_x86_64" >/dev/null || exit 1
          for file in *~*.ipk; do
          [ -e "$file" ] || continue
          # 构造新文件名，去除 ~ 字符
          new_file="$(echo "$file" | tr -d '~')"
          # 如果目标文件名已存在，则提示并跳过
          if [ -e "$new_file" ]; then
          echo "目标文件已存在，跳过: $new_file"
          continue
          fi
          # 重命名文件
          mv "$file" "$new_file"
          echo "已重命名: $file -> $new_file"
          done
          popd >/dev/null
          pushd "openlist2_aarch64_cortex-a53" >/dev/null || exit 1
          for file in *~*.ipk; do
          [ -e "$file" ] || continue
          # 构造新文件名，去除 ~ 字符
          new_file="$(echo "$file" | tr -d '~')"
          # 如果目标文件名已存在，则提示并跳过
          if [ -e "$new_file" ]; then
          echo "目标文件已存在，跳过: $new_file"
          continue
          fi
          # 重命名文件
          mv "$file" "$new_file"
          echo "已重命名: $file -> $new_file"
          done
          popd >/dev/null
          
      - name: Create install.sh scripts
        run: |
          cat <<EOF > openlist2_x86_64/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install *.ipk
          EOF
          chmod +x openlist2_x86_64/install.sh
          cp openlist2_x86_64/install.sh openlist2_aarch64_cortex-a53/install.sh
          
      - name: Move openlist2 directories to makeself
        run: |
          mv openlist2_x86_64 makeself/
          mv openlist2_aarch64_cortex-a53 makeself/
      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh openlist2_x86_64/ openlist2_${{ env.LATEST_TAG }}_x86_64.run "by github action" ./install.sh
          ./makeself.sh openlist2_aarch64_cortex-a53/ openlist2_${{ env.LATEST_TAG }}_aarch64_cortex-a53.run "by github action" ./install.sh
          
      - name: Check file sizes
        run: |
          ls -lh makeself/openlist2_*.run
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: openlist2
          name: "luci-app-openlist2"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "[![Github](https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.cn/archives/1)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
